### ISSUE TITLE
Confidence interval boxes don't extend all the way to the top of the plot

### ISSUE THREAD

**Issue by helenajr** [helenajr/Non-Elective-Flow-Simulation#5]
https://github.com/helenajr/Non-Elective-Flow-Simulation/blob/ad3a1498c9be76356e318a110bf3f757752a5b3c/app/app.py#L43-L101

Think this is because ymax is being recalculated after the boxes are drawn? Tried various things, but can't seem to change this.

![image](https://github.com/user-attachments/assets/f79da753-2c9a-4c4f-9c49-560029b7fe92)

**Comment by FushigiOoka** [comment]
Hello.

I believe the following will work for your intended purpose of filling the box to the top of the graph.
Suggestion to change the code from line 85 to the following. Please note that y_min and y_max does not need to be defined in axvspan, as they have a default value of 0 and 1 (y_lim).

for ci in ci_ranges: 
    plt.axvspan(
         ci["lower"],  
         ci["upper"],  
         y_min,
         y_max,  
         color=ci["color"],  
         alpha=0.2,  
         zorder=0 
     )

**Comment by helenajr** [comment]
That worked! Thanks so much!
